import Card from "@/components/ui/Card";
import ListPagination from "@/components/ui/ListPagination";
import { IAllList, IAllMedia } from "@/types/allList";
import { fetchFromAPI } from "@/utils/fetchApi";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Popular Movies - Movies App",
  description: "Generated by create next app",
};

type SearchParams = Promise<{ [key: string]: string | string[] | undefined }>;

export default async function PopularPage(props: {
  searchParams: SearchParams;
}) {
  const response = await fetchFromAPI<IAllMedia>(
    `movie/popular?api_key=${process.env.API_KEY}`,
  );

  return (
    <main className="mt-24 w-full px-2 lg:px-5">
      <section>
        <div className="my-16 lg:w-[60%]">
          <h1 className="text-3xl font-semibold">Popular Movies</h1>
          <p className="mt-2 text-medium text-gray-700 dark:text-gray-400 lg:text-lg">
            Dive into the world of popular movies that have captured the hearts
            of audiences worldwide. From blockbuster hits to critically
            acclaimed films, discover what's trending in the cinematic universe.
          </p>
        </div>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
          {response?.results.map((data: IAllList, i: number) => {
            return <Card data={data} key={i} mediatype="movies" />;
          })}
        </div>
        {response?.total_pages !== 1 && (
          <Suspense fallback={<p>Loading...</p>}>
            <ListPagination totalPage={response?.total_pages} />
          </Suspense>
        )}
      </section>
    </main>
  );
}
