import Card from "@/components/ui/Card";
import ListPagination from "@/components/ui/ListPagination";
import { IAllList } from "@/types/allList";
import { Metadata } from "next";
import { Suspense } from "react";

type SearchParams = Promise<{ [key: string]: string | string[] | undefined }>;

export const metadata: Metadata = {
  title: "Trending Now - Movie App",
  description: "Generated by create next app",
};

export default async function TrendingTvShowsPage({
  searchParams,
}: {
  searchParams: SearchParams;
}) {
  const { page } = await searchParams;

  const response = await fetch(
    `https://api.themoviedb.org/3/trending/tv/day?api_key=${process.env.API_KEY}&page=${page === undefined ? 1 : page}`,
  );

  const { results } = await response.json();

  return (
    <main className="mt-24 w-full px-2 lg:px-5">
      <section>
        <div className="my-16 lg:w-[60%]">
          <h1 className="text-3xl font-semibold">Trending TV Shows</h1>
          <p className="mt-2 text-medium text-gray-700 dark:text-gray-400 lg:text-lg">
            Catch up with the world and see what TV shows are currently
            trending. From viral sensations to critically acclaimed series, find
            out what&apos;s capturing viewers&apos; attention.
          </p>
        </div>
        <div className="mt-10 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
          {results?.map((data: IAllList, i: number) => {
            return <Card data={data} key={i} mediatype={"tv"} />;
          })}
        </div>
        <Suspense fallback={<p>Loading...</p>}>
          <ListPagination totalPage={500} />
        </Suspense>
      </section>
    </main>
  );
}
