import Card from "@/components/ui/Card";
import ListPagination from "@/components/ui/ListPagination";
import { IAllList, IAllMedia } from "@/types/allList";
import { fetchFromAPI } from "@/utils/fetchApi";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Now Playing Movies- Movies App",
  description: "Generated by create next app",
};

type SearchParams = Promise<{ [key: string]: string | string[] | undefined }>;

export default async function NowPlayingPage(props: {
  searchParams: SearchParams;
}) {
  const { page } = await props.searchParams;

  const response = await fetchFromAPI<IAllMedia>(
    `movie/now_playing?api_key=${process.env.API_KEY}&page=${page !== undefined ? page : "1"}`,
  );

  return (
    <main className="mt-24 w-full px-2 lg:px-5">
      <section>
        <div className="my-16 lg:w-[60%]">
          <h1 className="text-3xl font-semibold">Now Playing Movies</h1>
          <p className="mt-2 text-medium text-gray-700 dark:text-gray-400 lg:text-lg">
            Catch the latest movies now playing in theaters near you. Experience
            the magic of cinema with current hits.
          </p>
        </div>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
          {response?.results.map((data: IAllList, i: number) => {
            return <Card data={data} key={i} mediatype="movies" />;
          })}
        </div>
        {response?.total_pages !== 1 && (
          <Suspense fallback={<p>Loading...</p>}>
            <ListPagination totalPage={response?.total_pages} />
          </Suspense>
        )}
      </section>
    </main>
  );
}
